//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locaris_LJKDev_EF_MVC_EFStudy_01_20200702
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LJK_SQLServerDBEntities : DbContext
    {
        public LJK_SQLServerDBEntities()
            : base("name=LJK_SQLServerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaFull> AreaFull { get; set; }
        public virtual DbSet<User_Info> User_Info { get; set; }
        public virtual DbSet<VIP_Info> VIP_Info { get; set; }
    }
}
