//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locaris_LJKDev_EF_MVC_EFStudy_01_20200702
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public Nullable<bool> User_Gender { get; set; }
        public Nullable<int> User_Age { get; set; }
        public string User_Address { get; set; }
        public Nullable<System.DateTime> User_Birthday { get; set; }
        public string User_Remark { get; set; }
        public Nullable<decimal> User_Money { get; set; }
        public Nullable<System.Guid> User_GUIDDemo { get; set; }
        public Nullable<int> User_Pwd { get; set; }
    }
}
