//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locaris_LJKDev_EF_MVC_EFStudy_01_20200702
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIP_Info
    {
        public int VIP_ID { get; set; }
        public string VIP_Name { get; set; }
        public Nullable<int> VIP_Age { get; set; }
        public Nullable<bool> VIP_Gender { get; set; }
        public string VIP_Adress { get; set; }
        public Nullable<decimal> VIP_Money { get; set; }
        public Nullable<System.TimeSpan> VIP_Time { get; set; }
    }
}
